# This program generates an srad file with forbid constraints for overfly
# routes in China. 

def generateSRAD(overflyRules, forbidden_entry_segs, forbidden_segs, points):

    srad = open('_CHINA_FORBID_OVERFLIGHT.srad', 'w')

    srad.write(
              "(SuluRad 1 0)\n"
              "(Restriction \"FORBIDDEN ENTRY SEGMENTS\" F \"Forbidden rules for China overflight\" \"Auto generated by script\" ()\n" 
              )
    for line in overflyRules:
        srad.write(line)
    srad.write( "\n(\n"
                "(\n")
    for entry_seg in forbidden_entry_segs:
        srad.write("  (Segment N (FL 0) (FL99000) "+entry_seg['airway']+" "+entry_seg['from']+" "+points[entry_seg['from']]['lon'] +" "+points[entry_seg['from']]['lat']+" "+entry_seg['to']+" "+points[entry_seg['to']]['lon'] + " " +points[entry_seg['to']]['lat']+")\n")
    srad.write(")))\n\n")

    for entry_node in forbidden_segs:
        srad.write(
            "(Restriction \""+entry_node+"\" F \"Forbidden segments when entering in "+entry_node+"\" \"Generated by script\" ()\n"
        )
        srad.write("  ((Point N (FL 0) (FL 99000) "+entry_node +" "+points[entry_node]['lon']+" "+points[entry_node]['lat']+"))")
        
        current_segs = forbidden_segs[entry_node]
        for seg in current_segs
            srad.write("  ")

    srad.write(")")
    srad.close()
